// Boon icons (piece `boons`): 16x16 pixel art, one per boon, authored as text in palette
// letters. Drawn at an integer scale with an automatic 1-pixel ink outline, so the art itself
// never needs one. Cached as canvases per (id, scale, tint).
//
//   drawIcon(g, 'chain-spark', x, y, { scale: 3, outline: 'ink', tint: null })
//   iconCanvas(id, scale, opts) -> canvas (w = h = 16 * scale + 2 * scale)

import { css } from '../render/palette.js';

const KEY = {
  w: 'white', t: 'torch', g: 'gold', f: 'flame', e: 'ember', r: 'red', b: 'blood',
  s: 'sky', c: 'cyan', T: 'teal', n: 'navy', B: 'blue',
  x: 'bone', F: 'frost', G: 'fog', M: 'mist', S: 'slate', v: 'violet', d: 'dusk', h: 'shadow',
  o: 'rose', p: 'plum', l: 'leaf', m: 'moss', W: 'wood', L: 'woodLight', P: 'stoneLight', O: 'stone', k: 'ink',
};

export const ICONS = {
  'keen-edge': `
..............ww
.............wFw
............wFS.
...........wFS..
..g.......wFS...
.gtg.....wFS....
..g.....wFS.....
.......wFS......
......wFS.......
..g..wFS........
..ggwFS.........
...gWg..........
..gLgWg.........
.WL...g.........
WL..............
L...............`,
  'fleet-foot': `
.ww.............
wFFw............
wFsFw...........
.wFsFw.LLLLL....
..wFsFwLLLLW....
...wFFwLLLLW....
....wwLLLLLW....
.......LLLLW....
.ss....LLLLLLL..
.......LLLLLLLLW
..sss..LLLLLLLLW
.......WWWWWWWWW
........MMM..MMM
.ss.............
................
................`,
  'soul-hunger': `
.......w........
......wsc.......
.....wssTc......
....wwssTTc.....
...wwsssTTTc....
...wssssTTTc....
....wssTTTc.....
.....wsTTc......
......wTc.......
.......c........
..s.........s...
...ss.....ss....
.....sssss......
..c..........c..
...cc......cc...
.....cccccc.....`,
  'bulwark': `
................
...FFFFFFFFFF...
..FwwwwwwwwwwF..
..FwGGGGGGGGMF..
..FwGGGsGGGGMF..
..FwGGsssGGGMF..
..FwGsGsGsGGMF..
..FwGGGsGGGGMF..
..FwGGsGsGGGMF..
...FwGGGGGGMF...
...FwGGGGGGMF...
....FwGGGGMF....
.....FwGGMF.....
......FwMF......
.......FF.......
................`,
  'kindling': `
.......e........
.......ee.......
......efe.......
......effe...e..
.....effe....ee.
....efffe...efe.
...eefgffe..efe.
...effggfe.efe..
..effgggffeffe..
..efggtggfffe...
..efgttwtgffe...
..efgtwwtgfe....
...efgttgfe.....
....effffe......
.....eeee.......
................`,
  'heavy-hand': `
................
...OPPOPPOPPO...
..OPxPPxPPxPPO..
..OPPPPPPPPPPO..
..OPxPPxPPxPPO..
..OPPPPPPPPPPO..
..OOOOOOOOOOPO..
.OPxxxxxxPPPPO..
.OPPPPPPPPPPOO..
..OOOOOOOOOO....
...SMMMMMMMS....
...SMMMMMMMS....
...SSSSSSSSS....
.x...........x..
x.x.........x.x.
................`,
  'chain-spark': `
..........wwwwc.
.........wsssc..
........wsssc...
.......wsssc....
......wsssc.....
.....wsssswwwc..
....wwwwwsssc...
.........wssc...
........wssc....
.......wssc.....
......wsc.......
.....wsc....w...
....wc.....wsw..
...wc.......w...
..c.............
................`,
  'ember-trail': `
................
...........e....
..........efe...
..........efe...
.........efgfe..
.........egtge..
......e...eee...
.....efe........
.....efe........
....efgfe.......
.e..egtge.......
efe..eee........
efe.............
egfe............
.ee.............
SSSSSSSSSSSSSSSS`,
  'leech': `
.......r........
.......r........
......rrr.......
......rrr.......
.....rrrrr......
.....rorrr......
....rowrrrr.....
....rowrrrrr....
...rrorrrrrrb...
...rrrrrrrrrb...
...rrrrrrrrbb...
....rrrrrrbb....
.....bbbbbb.....
................
..r..........r..
.rrr........rrr.`,
  'storm-dash': `
................
.....GGGG.......
...GGFFFFGG.....
..GFFFwwFFFGG...
.GFFwwwwFFFFFG..
.GMMMMMMMMMMMG..
..MMMMMMMMMMM...
.......wsc......
......wsc.......
.....wsssswc....
.......wssc.....
......wsc.......
.....wsc........
....wc..........
....c...........
................`,
  'echo-blade': `
...........c..ww
..........cT.wFw
.........cT.wFS.
........cT.wFS..
.......cT.wFS...
......cT.wFS....
.....cT.wFS.....
....cT.wFS......
...cT.wFS.......
..cT.wFS........
..T..gS.........
...c.gWg........
..c.gLgWg.......
.c.WL...g.......
..WL............
.L..............`,
  'moon-wave': `
................
......wwww......
....wwssss......
...wsssc........
..wssc......s...
..wsc..........s
.wssc.....ss....
.wsc............
.wsc.......sss..
.wssc...........
..wsc.....ss....
..wssc.........s
...wsssc....s...
....wwssss......
......wwww......
................`,
  'ember-orbit': `
................
.....SSSSSS.....
...SS......SS...
..S.........ege.
.S.........egtge
.S..........ege.
S......vv......S
S.....vxxv.....S
S.....vxxv.....S
S......vv......S
.ege..........S.
egtge........S..
.ege........S...
...SS......SS...
.....SSSSSS.....
................`,
  'reaper': `
.....xxxxxxx....
...xxFFFFFFxx...
..xF.......Fxx..
.xF.........W.x.
.x.........W....
..........W.....
.........W......
........W.......
...xxxx.W.......
..xxxxxxW.......
..xkxxkxW.......
..xxxxxW........
..xxkkxW........
...x.xW.........
.....W..........
....W...........`,
  'starfall': `
.t..............
..g.............
...g............
....f....w......
.....f..wtw.....
......gttwttg...
...ggttttwttttgg
....gtttwwwtttg.
.....gttwwwttg..
......gttwttg...
.....gtg...gtg..
.....gg.....gg..
....g.........g.
................
..x...x.....x...
.xxxxxxx.xxxxxx.`,
  'phoenix': `
................
.......ff.......
......fttf......
e.....ftwf.....e
ee....ftff....ee
efe..ffgff...efe
.efe.fgggff.efe.
.effegggggeffe..
..effgggggffe...
...efggtggfe....
....efgggfe.....
.....efgfe......
......efe.......
.....e.e.e......
....e..e..e.....
................`,
};

// a couple of small extra glyphs for the UI
ICONS.shard = `
................
................
.......w........
......wsc.......
.....wssTc......
....wwssTTc.....
....wsssTTc.....
....wssTTTc.....
.....wsTTc......
......wTc.......
.......c........
................
................
................
................
................`;
ICONS.heart = `
................
................
...rrr...rrr....
..rowrr.rrrrr...
..rowrrrrrrrb...
..rorrrrrrrrb...
..rrrrrrrrrrb...
...rrrrrrrrb....
....rrrrrrb.....
.....rrrrb......
......rrb.......
.......b........
................
................
................
................`;
ICONS.skull = `
................
................
.....xxxxx......
....xxxxxxx.....
...xxxxxxxxx....
...xkkxxxkkx....
...xkkxxxkkx....
...xxxxkxxxx....
....xxxxxxx.....
....xkxkxkx.....
................
................
................
................
................
................`;

function parse(src) {
  const rows = src.split('\n').map((r) => r.trim()).filter((r) => r.length);
  const px = [];
  for (let y = 0; y < 16; y++) {
    const row = (rows[y] || '').padEnd(16, '.').slice(0, 16);
    for (let x = 0; x < 16; x++) {
      const ch = row[x];
      if (ch === '.' || ch === ' ') continue;
      const name = KEY[ch];
      if (!name) throw new Error(`icons: no key for "${ch}"`);
      px.push([x, y, name]);
    }
  }
  return px;
}

const parsed = {};
const cache = new Map();

/**
 * A canvas with the icon drawn at `scale`, framed by a 1-icon-pixel margin for the outline.
 *   outline: palette name or null.  tint: draw every pixel in one colour (silhouettes, flashes).
 *   dim: true draws the art in muted colours (a spent one-shot boon).
 */
export function iconCanvas(id, scale = 1, { outline = 'ink', tint = null, dim = false } = {}) {
  const key = `${id}|${scale}|${outline}|${tint}|${dim}`;
  let c = cache.get(key);
  if (c) return c;
  const src = ICONS[id];
  if (!src) return null;
  const px = parsed[id] ??= parse(src);
  c = document.createElement('canvas');
  c.width = c.height = 18 * scale;
  const g = c.getContext('2d');
  const set = new Set(px.map(([x, y]) => x + ',' + y));
  if (outline) {
    g.fillStyle = css(outline);
    for (const [x, y] of px) for (const [dx, dy] of [[-1, 0], [1, 0], [0, -1], [0, 1]]) {
      if (set.has((x + dx) + ',' + (y + dy))) continue;
      g.fillRect((x + dx + 1) * scale, (y + dy + 1) * scale, scale, scale);
    }
  }
  const DIM = { white: 'fog', torch: 'mist', gold: 'mist', flame: 'slate', ember: 'slate', sky: 'mist', cyan: 'slate', frost: 'mist', bone: 'mist', fog: 'slate', red: 'violet', rose: 'slate' };
  for (const [x, y, name] of px) {
    g.fillStyle = css(tint ?? (dim ? (DIM[name] ?? 'violet') : name));
    g.fillRect((x + 1) * scale, (y + 1) * scale, scale, scale);
  }
  cache.set(key, c);
  return c;
}

/** Draw an icon with its top-left (outline margin included) at (x, y). Returns its size. */
export function drawIcon(g, id, x, y, opts = {}) {
  const c = iconCanvas(id, opts.scale ?? 1, opts);
  if (!c) return 0;
  g.drawImage(c, Math.round(x), Math.round(y));
  return c.width;
}
